### ISSUE TITLE
wrapping in mobile (Nexus 4) a bit overzealous

### ISSUE THREAD

**Issue by criscristina** [openoakland/EarlyOakland#12]
The text in checkbox fields are wrapping too early.

![screenshot_2013-04-30-20-21-13](https://f.cloud.github.com/assets/3180799/447700/6b2a254e-b210-11e2-93c6-b6476526856f.png)

**Comment by max-mapper** [comment]
I'd guess this is due to a % in the css rather than a pixel value/fluid solution

**Comment by fsargent** [comment]
Cannot reproduce
