### ISSUE TITLE
Add in licensed child care providers

### ISSUE THREAD

**Issue by spjika** [openoakland/EarlyOakland#13]
http://www.ccld.ca.gov/docs/ccld_search/ccld_search.aspx
Data are available

**Comment by spjika** [comment]
Added geocoded csv file to repo as oakchildcare.csv. Needs some field formatting to fit regular use, then new feature type, append to geojson file and create new checkbox for this facility type: Child Care Centers

**Comment by fsargent** [comment]
Site no longer works...
![image](https://cloud.githubusercontent.com/assets/273880/25862993/080827d4-34b8-11e7-8df9-37cac028bab6.png)
