### ISSUE TITLE
More sponsors

### ISSUE THREAD

**Issue by spjika** [openoakland/EarlyOakland#16]
Add this intro and more sponsors to bottom section- waiting for clarification about this supplanting sponsors or a new section.

Early Supporters

The following organizations made this effort possible by supporting our first Swing into Preschool campaign that laid the foundation for EarlyOakland.Org

We wish to formally recognize:

Alameda County Supervisor Keith Carson District 5 

Alameda County Early Care Education Planning Council 

First 5 Alameda County

Oakland Unified School District

The Dave and Lucile Packard Foundation

The San Francisco Foundation 

Many thanks!!!!

**Comment by fsargent** [comment]
@spjika Do we need more info to put this up?

**Comment by fsargent** [comment]
I think these are already on here.
