### ISSUE TITLE
Create FAQ and Learn More content

### ISSUE THREAD

**Issue by spjika** [openoakland/EarlyOakland#18]
there's a few paragraphs of text about the enrollment process and about early childhood services to add- somewhere- may be best to add these as headings with drop down content if people want to dig into this stuff while not blowing out the length of the single page?

**Comment by spjika** [comment]
FAQ content from the Oak Ed Cabinet is in this doc:
https://docs.google.com/document/d/1WmvEGfpf8KPa6jzgIwLsgy7ZPCL6aCGPJMDyp7da06Q/edit?usp=sharing

To be honest this may need some cleaning and simplification, it's written a little wonkish- the site it aimed at folks with pretty low literacy levels so it needs simple content.

**Comment by fsargent** [comment]
Looks good enough..!
