### ISSUE TITLE
Filtering logic rework needed

### ISSUE THREAD

**Issue by spjika** [openoakland/EarlyOakland#3]
We need to tweak the filter queries to operate like this:
*Default- all sites should show on the map - ideally with all the TYPES ticked ON as a default?

*Filters should be additive, not exclusive within each set - use OR:
So if you select 3-5 Years alone, those sites will be visible and will be searched. If you then add 3-8 Years it will use an OR to show/search all sites with a YES in the 3-5 and in the 3-8 field. There are no exclusions if a site does one- it can do the other too so both need to show.

Also with the TIMES - these should be additive with the ages- so if 3-5 is ticked and shows, if you select a FULL DAY then this should show sites with 3-5 as YES AND also with FULL DAY as YES. But withIN the TIMES and the AGES they need to operate as ORs- to adding 1/2 Day to the FULL DAY filter would show all sites with both options.

Is this clear enough? The premise is that a user will want to see what sites exist in total when first getting to the site, then perhaps narrow it down by their kids age, and then many by the time of day they need. If this creates problems with the js in the template we should talk about the defaults to make it clearer for typical parent use cases.
thanks yall!

**Comment by max-mapper** [comment]
fixed
