### ISSUE TITLE
line up data in popups

### ISSUE THREAD

**Issue by max-mapper** [openoakland/EarlyOakland#6]
![Screen Shot 2013-03-13 at 2 05 49 PM](https://f.cloud.github.com/assets/39759/256129/cda2800a-8c21-11e2-9fe1-792fd5f4a291.png)

it doesn't line up all the lines correctly

**Comment by jasonjlock** [comment]
Would you be open to changing how this data is displayed a little bit?
![oak-map](https://f.cloud.github.com/assets/1526861/262091/5c142c64-8d15-11e2-8670-fb5a42119897.png)

**Comment by max-mapper** [comment]
that looks great! I can merge a pull request or even give you push access to the repo

**Comment by jasonjlock** [comment]
Right on :) I'll submit what I have tomorrow.

**Comment by spjika** [comment]
How did those changes go, love to get them incorporated, looks fantastic!

Spike
